apiVersion: v1
kind: Secret
metadata:
  name: {{ include "model-registry.fullname" . }}-registry-db
  namespace: {{ .Values.registryNamespace }}
type: Opaque
data:
  database-name: {{ .Values.database.name | b64enc }}
  database-password: {{ .Values.database.password | b64enc }}
  database-user: {{ .Values.database.user | b64enc }}