apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "model-registry.fullname" . }}-metadata-mysql
  namespace: {{ .Values.dbNamespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.database.volumeSize }}