apiVersion: v1
kind: Secret
metadata:
  name: {{ include "model-registry.fullname" . }}-db-secrets
  namespace: {{ .Values.dbNamespace }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.database.rootPassword | b64enc }}
  MYSQL_USER: {{ .Values.database.user | b64enc }}
  MYSQL_PASSWORD: {{ .Values.database.password | b64enc }}