apiVersion: v1
kind: Service
metadata:
  name: {{ include "model-registry.fullname" . }}-db
  namespace: {{ .Values.dbNamespace }}
  labels:
    {{- include "model-registry.labels" . | nindent 4 }}
    component: db
spec:
  ports:
    - name: dbapi
      protocol: TCP
      port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}
  type: ClusterIP
  selector:
    {{- include "model-registry.selectorLabels" . | nindent 4 }}
    component: db