{{- if and (not .Values.admin.existingSecret) .Values.admin.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea.fullname" . }}-admin
type: Opaque
data:
  adminPassword: {{ .Values.admin.password | b64enc }}
{{- end }}
