{{- if and (not .Values.users.existingSecret) .Values.users.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gitea.fullname" . }}-users
type: Opaque
data:
  userPassword: {{ .Values.users.password | b64enc }}
{{- end }}
